apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: facu077/helloworld
      context: ../helloWorld
      jib: {}
  tagPolicy:
    envTemplate:
      template: '{{.IMAGE_NAME}}:latest'
deploy:
  kustomize: {}
